---
- name: update apt cache
  apt: update_cache=yes
       cache_valid_time=900
  tags: instalL_clamav

- name: install clamav
  apt: name={{ item }}
  with_items: clamav_packages
  notify: Initialize antivirus database
  tags: instalL_clamav

- name: remove default clamav-unofficial-sigs cron file
  file: path=/etc/cron.d/clamav-unofficial-sigs
        state=absent
  tags: instalL_clamav

- name: Use syslog
  lineinfile: dest=/etc/clamavfreshclam.conf
              regexp=^UpdateLogFile
              state=absent
  tags: instalL_clamav

- name: Enable logging timestamp
  lineinfile: dest=/etc/clamav/freshclam.conf
              line='LogTime yes'
  tags: instalL_clamav

- name: Configure cron clamav cron jobs
  include: cron.yml
  when: clamav_enable_cron == true
  tags:
  - instalL_clamav
  - clamav_cron
